/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS.FUNCION;

import DAO.clienteDAO;
import java.awt.Color;
import model.modelCliente;

/**
 *
 * @author Alunos
 */
public class viewFunctionPesqCliente extends javax.swing.JFrame {

    modelCliente c = new modelCliente();
    clienteDAO cdao = new clienteDAO();
    
    public viewFunctionPesqCliente() {
        initComponents();
        jPanel3.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        busca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        nasc = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        btnALt = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        cpf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(810, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesq.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 30, 40));

        busca.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        busca.setForeground(new java.awt.Color(204, 204, 204));
        busca.setText("              Buscar Cliente");
        busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscaMouseClicked(evt);
            }
        });
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });
        jPanel1.add(busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 160, 20));

        jButton1.setForeground(new java.awt.Color(0, 206, 209));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 206, 209));
        jLabel3.setText("Nome");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 110, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 206, 209));
        jLabel4.setText("Data de Nascimento");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, 20));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 206, 209));
        jLabel5.setText("Telefone");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 206, 209));
        jLabel6.setText("CPF");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 40, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 206, 209));
        jLabel7.setText("Endereço");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, 20));

        nome.setEditable(false);
        nome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 270, 20));

        nasc.setEditable(false);
        nasc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 270, 20));

        tel.setEditable(false);
        tel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 270, 20));

        end.setEditable(false);
        end.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        end.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 270, 20));

        btnALt.setForeground(new java.awt.Color(0, 206, 209));
        btnALt.setText("Alterar");
        btnALt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALtActionPerformed(evt);
            }
        });
        jPanel3.add(btnALt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 363, 70, 30));

        btnSalva.setText("Salvar");
        btnSalva.setEnabled(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 363, 70, 30));

        btnexcluir.setForeground(new java.awt.Color(0, 206, 209));
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 363, 70, 30));

        cpf.setEditable(false);
        cpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 270, 20));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 206, 209));
        jLabel10.setText("Email");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 50, 20));

        email.setEditable(false);
        email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 270, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 206, 209));
        jLabel11.setText("ID");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 20));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 270, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 810, 440));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/agif2opt.gif"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, 850, 490));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        c.setCpf(busca.getText());
        cdao.PesquisarPorcpfcliente(c);
        id.setText(String.valueOf(c.getId()));
        nome.setText(c.getNome());
        cpf.setText(c.getCpf());
        tel.setText(c.getTelefone());
        end.setText(c.getEndereco());
        nasc.setText(c.getNascimento());
        email.setText(c.getEmail());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        viewPrincipalFuncion vf  = new viewPrincipalFuncion();
        vf.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnALtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALtActionPerformed
     btnALt.setEnabled(true);
     nome.setEditable(true);
     nasc.setEditable(true);
    email.setEditable(true);
     end.setEditable(true);
     cpf.setEditable(true);
     tel.setEditable(true);
     
         
    }//GEN-LAST:event_btnALtActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        c.setNome(nome.getText());
        c.setCpf(cpf.getText());
        c.setEndereco(end.getText());
        c.setNascimento(nasc.getText());
        c.setEmail(email.getText());
        c.setTelefone(tel.getText());
        cdao.AlterarCliente(c);
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        c.setId(Integer.parseInt(id.getText()));
        cdao.ExcluirCliente(c);
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void buscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaMouseClicked
busca.setText("");
busca.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_buscaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFunctionPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFunctionPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFunctionPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFunctionPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFunctionPesqCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnALt;
    private javax.swing.JButton btnSalva;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JTextField busca;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField end;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nasc;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
