/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS.FUNCION;

import DAO.clienteDAO;
import DAO.filmeDAO;
import DAO.itenslocadosDAO;
import DAO.locacaoDAO;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.modelCliente;
import model.modelFilme;
import model.modelItensLocados;
import model.modelLocacao;

/**
 *
 * @author Alunos
 */
public class viewFunctionLoc extends javax.swing.JFrame {

    /**
     * Creates new form viewFunctionLoc
     */
    DefaultListModel model = new DefaultListModel();
    locacaoDAO ldao = new locacaoDAO();
    modelLocacao l = new modelLocacao();
    modelCliente cl = new modelCliente();
    clienteDAO cdao = new clienteDAO();
    itenslocadosDAO ildao = new itenslocadosDAO();
    modelItensLocados mil = new modelItensLocados();
    modelFilme f = new modelFilme();
    filmeDAO fdao = new filmeDAO();

    public viewFunctionLoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filmen = new javax.swing.JTextField();
        dtlocacao = new javax.swing.JTextField();
        dtdev = new javax.swing.JTextField();
        valorloc = new javax.swing.JTextField();
        CpfCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 206, 209));
        jLabel1.setText("CPF do Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 129, 140, 20));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 206, 209));
        jLabel2.setText("Filme");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 289, 90, 20));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 206, 209));
        jLabel3.setText("Data da Locação");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 169, 160, 20));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 206, 209));
        jLabel4.setText("Previsão de Devolução");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 199, 190, 20));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 206, 209));
        jLabel5.setText("Valor da Locação");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 229, 160, 20));

        filmen.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        filmen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        filmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmenActionPerformed(evt);
            }
        });
        jPanel1.add(filmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 300, 20));

        dtlocacao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        dtlocacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(dtlocacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 300, 20));

        dtdev.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        dtdev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        dtdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtdevActionPerformed(evt);
            }
        });
        jPanel1.add(dtdev, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 300, 20));

        valorloc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        valorloc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(valorloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 300, 20));

        CpfCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CpfCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(CpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 300, 20));

        jButton1.setForeground(new java.awt.Color(0, 206, 209));
        jButton1.setText("Adicionar Filme");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, -1));

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 100, 170));

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Remover Filme");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        jButton3.setText("Alugar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 363, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        viewPrincipalFuncion prn = new viewPrincipalFuncion();
        prn.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(72, 209, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(72, 209, 204));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.jList1.setModel(model);
        model.addElement(filmen.getText());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void filmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmenActionPerformed
        // TODO add your handling code here:
        //sql
        //insert into locacao ...
        //select max(id) as id from locacao 

        int teste = Integer.parseInt(jList1.getSize() + "");
        for (int x = 0; x < teste; x++) {
            String filme = jList1.getSelectedValuesList().get(x);
            //ghyhhyhyuu
        }
    }//GEN-LAST:event_filmenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /* this.jList1.setModel(model);
        model.removeElementAt(jList1.getSelectedIndices());*/
        Object sel = null;

        int[] selectedIx = this.jList1.getSelectedIndices();

        for (int i = 0; i < selectedIx.length; i++) {
            sel = jList1.getModel().getElementAt(selectedIx[i]);

            model.remove(selectedIx[i]);
        }

        System.out.println(sel);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        cl.setCpf(CpfCliente.getText());
        int id = cdao.pegaID(cl);
        l.setIdCliente(id);
        l.setDataLocacao(dtlocacao.getText());
        l.setDataDevolucao(dtdev.getText());
        l.setValor(Double.parseDouble(valorloc.getText()));
        ldao.locar(l);
        int idloc = ldao.PegaIdloc();
        int teste = model.size();
        int x = 0;

        while (x < teste) {

            String filme = model.getElementAt(x).toString();
            f.setNomeFilme(filme);
            fdao.PesquisarPorNome(f);
            int idf = f.getId();
           
            if(f.getEstoqueloja()<=f.getEstoquegeral()){
            mil.setIdFilme(idf);
            mil.setIdLocação(idloc);
            ildao.GuardarItens(mil);
            f.setEstoqueloja(f.getEstoqueloja()-1);
            fdao.AlterarFilme(f);
            }
            else{
                JOptionPane.showMessageDialog(null,"Esse filme não está no estoque");
            }
                        

            x++;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dtdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtdevActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_dtdevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFunctionLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFunctionLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFunctionLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFunctionLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFunctionLoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CpfCliente;
    private javax.swing.JTextField dtdev;
    private javax.swing.JTextField dtlocacao;
    private javax.swing.JTextField filmen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorloc;
    // End of variables declaration//GEN-END:variables
}
