/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS.FUNCION;

import DAO.filmeDAO;
import DAO.generoDao;
import java.sql.Time;
import java.util.List;
import javafx.scene.control.ComboBox;
import model.modelFilme;
import model.modelGenero;

/**
 *
 * @author Alunos
 */
public class viewFuncionCadastrarFilme extends javax.swing.JFrame {

    modelFilme f = new modelFilme();
    filmeDAO fdao = new filmeDAO();
    generoDao box = new generoDao();
    modelGenero g = new modelGenero();

    public viewFuncionCadastrarFilme() {
        initComponents();
        for (modelGenero mg : box.LerGenero()) {
            combobox.addItem(mg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        dtlanc = new javax.swing.JTextField();
        dur = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        estoque = new javax.swing.JTextField();

        jButton1.setText("Cadastrar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 206, 209));
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 206, 209));
        jLabel2.setText("Duração");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 20));

        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 370, 20));

        dtlanc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(dtlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 370, 20));

        dur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(dur, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 370, 20));

        combobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        combobox.setForeground(new java.awt.Color(0, 206, 209));
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 370, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 206, 209));
        jLabel3.setText("Descrição");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, 20));

        desc.setColumns(20);
        desc.setRows(5);
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 380, 80));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 206, 209));
        jLabel6.setText("Data de Lançamento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 206, 209));
        jLabel7.setText("Genero");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 140, 20));

        jButton2.setForeground(new java.awt.Color(0, 206, 209));
        jButton2.setText("Salvar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 206, 209));
        jLabel5.setText("Estoque");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, 20));

        estoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 370, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        viewPrincipalFuncion vf = new viewPrincipalFuncion();
        vf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        f.setNomeFilme(titulo.getText());
        f.setAnolancamento(dtlanc.getText());
        f.setTempoduracao(dur.getText());
        f.setEstoqueloja(Integer.parseInt(estoque.getText()));
       f.setEstoquegeral(Integer.parseInt(estoque.getText()));
        modelGenero mg = (modelGenero) combobox.getSelectedItem();
        String genero = mg.getGenero();

        f.setGenero(String.valueOf(box.pegaID(genero)));
        f.setDescricao(desc.getText());

        fdao.CadastrarFilme(f);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
    jButton2.setBackground(new java.awt.Color(72, 209, 204));
    jButton2.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new java.awt.Color(255,255,255));// TODO add your handling code here:
        jButton2.setForeground(new java.awt.Color(72,209,204));
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFuncionCadastrarFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> combobox;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextField dtlanc;
    private javax.swing.JTextField dur;
    private javax.swing.JTextField estoque;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
