/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS.FUNCION;

import DAO.clienteDAO;
import model.modelCliente;

/**
 *
 * @author Alunos
 */
public class viewFuncionCadastrarCliente extends javax.swing.JFrame {

    clienteDAO cdao = new clienteDAO();
    modelCliente c  = new modelCliente();
    
    public viewFuncionCadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        nasc = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        btbSalva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(72, 209, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 206, 209));
        jLabel8.setText("Nome");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 159, 130, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 206, 209));
        jLabel9.setText("Data de nascimento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 189, 230, 20));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 206, 209));
        jLabel10.setText("Telefone");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 219, 150, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 206, 209));
        jLabel11.setText("CPF");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 249, 110, 20));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 206, 209));
        jLabel12.setText("E-mail");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 279, 130, 20));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 206, 209));
        jLabel13.setText("Endereço");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 309, 150, 20));

        end.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        end.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 370, 20));

        nome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 370, 20));

        nasc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 370, 20));

        tel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 370, 20));

        cpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 370, 20));

        email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 370, 20));

        btbSalva.setForeground(new java.awt.Color(72, 209, 204));
        btbSalva.setText("Salvar");
        btbSalva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btbSalvaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btbSalvaMouseExited(evt);
            }
        });
        btbSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSalvaActionPerformed(evt);
            }
        });
        jPanel1.add(btbSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        viewPrincipalFuncion vf = new viewPrincipalFuncion();
        vf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btbSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSalvaActionPerformed
        c.setNome(nome.getText());
       c.setCpf(cpf.getText());
       c.setEmail(email.getText());
       c.setNascimento(nasc.getText());
       c.setEndereco(end.getText());
       c.setTelefone(tel.getText());
        
        cdao.CadastrarCliente(c);


    }//GEN-LAST:event_btbSalvaActionPerformed

    private void btbSalvaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbSalvaMouseEntered
btbSalva.setBackground(new java.awt.Color(72, 209, 204)); 
btbSalva.setForeground(new java.awt.Color(255,255,255));// TODO add your handling code here:
    }//GEN-LAST:event_btbSalvaMouseEntered

    private void btbSalvaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbSalvaMouseExited
btbSalva.setBackground(new java.awt.Color(255,255,255));
    btbSalva.setForeground(new java.awt.Color(72,209,204));        // TODO add your handling code here:
    }//GEN-LAST:event_btbSalvaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFuncionCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFuncionCadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbSalva;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField end;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nasc;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
