/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS.ADMIN;

import DAO.funcionarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.modelFuncionario;

/**
 *
 * @author Alunos
 */
public class viewPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipalAdmin
     */
    modelFuncionario f = new modelFuncionario();
        funcionarioDAO fdao = new funcionarioDAO();
    public viewPrincipalAdmin() {
        initComponents();
        busca.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnbusca = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inicial = new javax.swing.JPanel();
        busca = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnexcluir = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        nasc = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbusca.setBackground(new java.awt.Color(245, 245, 245));
        btnbusca.setForeground(new java.awt.Color(72, 209, 204));
        btnbusca.setText("Buscar");
        btnbusca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnbusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscaMouseExited(evt);
            }
        });
        btnbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaActionPerformed(evt);
            }
        });
        jPanel1.add(btnbusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 51, 30));

        buscar.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        buscar.setForeground(new java.awt.Color(204, 204, 204));
        buscar.setText(" Pesquisar Atendente (CPF)");
        buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 145, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesq.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        inicial.setBackground(new java.awt.Color(255, 255, 255));
        inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busca.setBackground(new java.awt.Color(255, 255, 255));
        busca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 206, 209));
        jLabel6.setText("Data De Nascimento");
        busca.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 206, 209));
        jLabel8.setText("Email");
        busca.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 90, 30));

        sal.setEditable(false);
        sal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 340, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 206, 209));
        jLabel7.setText("Salário Base");
        busca.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 140, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 206, 209));
        jLabel3.setText("Nome");
        busca.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 100, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 206, 209));
        jLabel4.setText("CPF");
        busca.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 206, 209));
        jLabel9.setText("Endereço");
        busca.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 120, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 206, 209));
        jLabel10.setText("Telefone");
        busca.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, 30));

        btnexcluir.setBackground(new java.awt.Color(255, 0, 51));
        btnexcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnexcluir.setText("Excluir");
        btnexcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        busca.add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 40, 30));

        btnAlt.setForeground(new java.awt.Color(72, 209, 204));
        btnAlt.setText("Alterar Dados");
        btnAlt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltMouseExited(evt);
            }
        });
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        busca.add(btnAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 120, 30));

        btnSalva.setForeground(new java.awt.Color(72, 209, 204));
        btnSalva.setText("Salvar");
        btnSalva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSalva.setEnabled(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });
        busca.add(btnSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 120, 30));

        nome.setEditable(false);
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 340, 20));

        nasc.setEditable(false);
        nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 340, 20));

        email.setEditable(false);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 340, 20));

        tel.setEditable(false);
        tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 340, 20));

        end.setEditable(false);
        end.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 340, 20));

        cpf.setEditable(false);
        cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 340, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        busca.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        id.setEditable(false);
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 209, 204)));
        busca.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 340, 20));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 206, 209));
        jLabel12.setText("ID");
        busca.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, 30));

        inicial.add(busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 810, 430));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/addatd.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        inicial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel1.setText("Adicionar Atendente");
        inicial.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        getContentPane().add(inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaActionPerformed
        busca.setVisible(true);
        
        f.setCpf(buscar.getText());
        fdao.PesquisarPorCpfFunc(f);
        
        nome.setText(f.getNome());
        cpf.setText(f.getCpf());
        email.setText(f.getEmail());
        tel.setText(f.getTelefone());
        end.setText(f.getEndereco());
        sal.setText(String.valueOf(f.getSalario()));
        nasc.setText(f.getNascimento());
        id.setText(String.valueOf(f.getId()));
    }//GEN-LAST:event_btnbuscaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        buscar.setText("");
        buscar.setForeground(Color.black);
    }//GEN-LAST:event_buscarMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        busca.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        viewAdminCadastrar cad = new viewAdminCadastrar();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnbuscaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscaMouseEntered
        btnbusca.setBackground(new java.awt.Color(72, 209, 204));
        btnbusca.setForeground(new java.awt.Color(245, 245, 245));
    }//GEN-LAST:event_btnbuscaMouseEntered

    private void btnbuscaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscaMouseExited
        btnbusca.setBackground(new java.awt.Color(245, 245, 245));
        btnbusca.setForeground(new java.awt.Color(72, 209, 204));

    }//GEN-LAST:event_btnbuscaMouseExited

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
btnSalva.setEnabled(true);
id.setEditable(true);
nome.setEditable(true);
nasc.setEditable(true);
email.setEditable(true);
tel.setEditable(true);
end.setEditable(true);
cpf.setEditable(true);
sal.setEditable(true);
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        
        f.setNome(nome.getText());
        f.setCpf(cpf.getText());
        f.setEmail(email.getText());
        f.setEndereco(end.getText());
        f.setNascimento(nasc.getText());
        f.setTelefone(tel.getText());
        f.setSalario(Double.parseDouble(sal.getText()));
        
        fdao.AlterarFunc(f);
        JOptionPane.showMessageDialog(null,"Dados alterados");
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        f.setId(Integer.parseInt(id.getText()));
        fdao.ExcluirFunc(f);
        JOptionPane.showMessageDialog(null,"Funcionário excluído");
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnAltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltMouseEntered
btnAlt.setBackground(new java.awt.Color(72, 209, 204));
    btnAlt.setForeground(new java.awt.Color(255,255,255));         // TODO add your handling code here:
    }//GEN-LAST:event_btnAltMouseEntered

    private void btnAltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltMouseExited
btnAlt.setBackground(new java.awt.Color(255,255,255));
    btnAlt.setForeground(new java.awt.Color(72,209,204));         // TODO add your handling code here:
    }//GEN-LAST:event_btnAltMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnSalva;
    private javax.swing.JButton btnbusca;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JPanel busca;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField end;
    private javax.swing.JTextField id;
    private javax.swing.JPanel inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nasc;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField sal;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
